# Generated by Django 3.0.5 on 2021-03-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenvisual',
            old_name='explicacion_detallada_alimentacion_inyecion',
            new_name='explicacion_detallada_alimentacion_inyeccion',
        ),
    ]
